name: Deploy to GitHub Pages
on:
  release:
    types: [published]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install modules
      run:
        yarn
    - name: Build
      run:
        yarn generate
    - name: Print resume
      run:
        node pdf.js
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: source
        BRANCH: master
        FOLDER: dist